import type { Metadata } from "next";
import "./globals.css";
import "@fontsource/montserrat/700.css";
import "@fontsource/montserrat/400.css";
import { Auth0Provider } from "@auth0/nextjs-auth0";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Auth0Provider>
      <body style={{backgroundColor: "#D9D9D9"}}>
        {children}
      </body>
      </Auth0Provider>
    </html>
  );
}
