import type { Metadata } from "next";
import "./globals.css";
import "@fontsource/montserrat/700.css";
import "@fontsource/montserrat/400.css";
import { Auth0Provider } from "@auth0/nextjs-auth0";
import styles from "@/styles/background.module.css";
import { auth0 } from "@/lib/auth0";
import NavBar from "@/components/NavBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const _ = await auth0.getSession();
  return (
    <html lang="en">
      <body style={{ backgroundColor: "#D9D9D9" }}>
        <Auth0Provider>
          <div
          style={{
            height: "100%",
            width: "100vw",
            display: "flex",
            justifyContent: "center",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          <div className={styles.dottedBg} />
          <div
            style={{
              overflow: "hidden",
              background: "linear-gradient(#008476, #d9d9d9)",
              opacity: 0.1,
              width: 200,
              height: "calc(100%)",
              position: "absolute",
              transform: "rotate(20deg)",
              zIndex: 1,
            }}
          />

          <div className={styles.banner}>
            <div className={styles.bannerText1}>Free Trial Lesson</div>
            <div className={styles.bannerText2}>Limited Time Offer!</div>
          </div>
          <NavBar/>
          {children}
        </div>
        </Auth0Provider>
      </body>
    </html>
  );
}
